### ISSUE TITLE
Implement actions/setup-java@v3

### ISSUE THREAD

**Issue by slepimis120** [slepimis120/seobe#4]
Right now, if we were to run a command such as "./mvnw build", it wouldn't work because we didn't set Java version with:
```     
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
```

- [x] Create a Go script that opens .yml file and adds additional Java job whenever there's a './mvnw' call.
- [x] Import and run Go script into Docker container
